[package]
name = "noir_aztec"
authors = ["aztec-labs"]
compiler_version = ">=0.18.0"
type = "lib"

[dependencies]
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages", tag="v5.0.0-nightly.20260222", directory="noir-projects/noir-protocol-circuits/crates/types" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
poseidon = { tag = "v0.2.6", git = "https://github.com/noir-lang/poseidon" }
